spring.application.name=aqar-admin

spring.datasource.url=jdbc:mysql://localhost:3306/aqar
spring.datasource.username=root
spring.datasource.password=zezopop2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.servlet.context-path=/api/admin
server.port=8086

# JWT
jwt.secret=k3F9pQ2vXz8mN1rT6wYnjsdlB7dC5eG9uJ2aI8oP3qM=
jwt.expiration.ms=86400000
spring.security.user.name=admin
spring.security.user.password=admin